### ISSUE TITLE
Different color between css and scss

### ISSUE THREAD

**Issue by LeusMaximus** [artifactdev/flatgrammer-theme#11]
I noticed that css and scss files have different colors for the same elements. 
For example:
http://prntscr.com/56zxca
http://prntscr.com/56zxw5

**Comment by artifactdev** [comment]
I will have an look on it. But can't promise anything.

**Comment by artifactdev** [comment]
Can't find a good fix for this which won't influence other languages in syntax highlighting. Feel free to fork the theme if you find a solution for your own and send a pull request.
