### ISSUE TITLE
Horizontal scrollbar is not visible

### ISSUE THREAD

**Issue by vuongdinhngoc** [artifactdev/flatgrammer-theme#13]
Horizontal scrollbar is not visible

![Horizontal scrollba](http://f.cl.ly/items/1F1z3f1B2f3T3L2x303v/Image%202014-12-11%20at%201.59.28%20AM.png)

**Comment by artifactdev** [comment]
I will habe a look in it tomorrow...I think a fix will be available tomorrow too.
