### ISSUE TITLE
No Folder Icons

### ISSUE THREAD

**Issue by jdubwelch** [artifactdev/flatgrammer-theme#2]
Do I have to do something special to get folder icons to display?

![No Folders](http://cl.ly/image/0w3t0j2Y1h1y/Image%202014-11-10%20at%209.15.16%20AM.png)

Being able to have bold folders would be awesome too.

**Comment by artifactdev** [comment]
Hello, it seems that you have Sublime Text 2. File and Foldericons are supported on Sublime Text 3 only.
