### ISSUE TITLE
Add option for small tab

### ISSUE THREAD

**Issue by vabatta** [artifactdev/flatgrammer-theme#3]
Hi,

first of all, congratulations for the good jobs! I really appreciate the icons for each type of files.
I great enhancement would be the possibilty to configure if you want to use a "small" or "normal" tabs; I mean, currently the tabs are big and I would like to have it just a little big less height (just to fit text in it).

Thanks

**Comment by artifactdev** [comment]
Thanks, I will try to add a configuration flag for your requested feature for smaller tabs.
