### ISSUE TITLE
Add to ColorSublime plugin

### ISSUE THREAD

**Issue by chamini2** [artifactdev/flatgrammer-theme#6]
Can we have the scheme added to [ColorSublime Plugin](https://github.com/Colorsublime/Colorsublime-Themes) for easier switch between schemes?

**Comment by artifactdev** [comment]
Sure, I will have a look and commit it to ColorSublime in the comming week.

**Comment by artifactdev** [comment]
Should be available via ColorSublime in the next days, after they merged my changes in there repo.
