### ISSUE TITLE
files color

### ISSUE THREAD

**Issue by LeusMaximus** [artifactdev/flatgrammer-theme#7]
Hi. Good theme.
I have two questions about sidebar.
1. Is there a setting for change font-size in sidebar?
2. Is it possible to change color of files or file extensions in sidebar, depending on the type of file?

**Comment by artifactdev** [comment]
1. Probably there will be an option for smaller/bigger font-size in the near future. Just tell me your best fitting needs.
2. No, and there will be no option like that in the future.

**Comment by artifactdev** [comment]
font-size of sidebar will be fixed with ticket #10
